# Generated by Django 4.1.7 on 2023-03-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('contents', models.TextField()),
                ('author', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')),
            ],
        ),
    ]
